name: DumprX on GITGUD
 
on:
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: "Direct Link of the ROM/Firmware to Dump"
        required: true
      EXTRA_CMD:
        description: "Any Extra Command to Run Before Dump"
        required: false

defaults:
  run:
    shell: bash

env:
  # ROM
  ROM_URL: ${{ github.event.inputs.ROM_URL }}

  # Gitlab
  PUSH_TO_GITLAB: true

  # Extra Command
  EXTRA_CMD: ${{ github.event.inputs.EXTRA_CMD }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
       - name: Cleanup
         uses: Van-Firmware-Dumps/slimhub_actions@main

       - name: Checkouts
         uses: actions/checkout@v4

       - name: Clone Our Firmware Dumper
         run: |
              git clone https://github.com/Van-Firmware-Dumps/DumprX.git DumprX

       - name: Setup DumprX's Environment
         working-directory: DumprX
         run: |

              sudo bash setup.sh
              sudo apt install -y f2fs-tools neofetch
              mkdir -p ~/.ssh
              ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
              ssh-keyscan -t rsa gitgud.io >> ~/.ssh/known_hosts
              git config --global user.name "VanVuong41429"
              git config --global user.email "vanvuong41429@gmail.com"

       - name: Setup Config envs
         working-directory: DumprX
         run: |
              echo "${{ secrets.GITGUD_TOKEN }}" > .gitlab_token  # Only for Gitlab
              echo "Van-Firmware-Dumps" > .gitlab_group  # Only for Gitlab
              echo "gitgud.io" > .gitlab_instance  # Only for Gitlab
              echo "${{ secrets.PRIV_SSH_KEY }}" > ~/.ssh/id_rsa  # Only for Gitlab
              echo "${{ secrets.BOT_TOKEN }}" > .tg_token
              echo "@VanFirmwareDumps" > .tg_chat
              chmod 600 ~/.ssh/id_rsa

       - name: Run the Extra Command
         working-directory: DumprX
         run: |
              $EXTRA_CMD
              df -h
              pip3 install git+https://github.com/martinetd/samloader.git
              samloader -m SM-E055F -r INS -i 353099641279323 download -v E055FXXU1AXH4/E055FODM1AXH4/E055FXXU1AXH3/E055FXXU1AXH4 -O .
              samloader -m SM-E055F -r INS -i 353099641279323 decrypt -v E055FXXU1AXH4/E055FODM1AXH4/E055FXXU1AXH3/E055FXXU1AXH4 -i $(ls *.enc*) -o firmware.zip
              rm $(ls *.enc*)
              df -h

       - name: Start Dumping
         working-directory: DumprX
         run: |
              ./dumper.sh "$ROM_URL"
